language: python
python:
        - "3.5"
services:
        - postgresql
addons:
        postgresql: "9.6"
install:
        - pip install -r requirements.txt
        - python setup.py bdist_egg
script:
        - python manage.py test
